# -*- coding: utf-8 -*-
"""Eleitores da Paraíba

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pS41ha_TNrD8YovQ1TViPEfWreopYugg
"""

import numpy as np
import geopandas as gpd
import folium

import pandas as pd
eleitorado = pd.read_csv('/content/tabelaEleitoradoPorMunicipioSexo.csv')

eleitorado = eleitorado.sort_values(by='Município')
uijeleitorado = eleitorado.reset_index(drop=True)

eleitorado

# prompt: Abrir planilha dbf

df = gpd.read_file('BR_Municipios_2024.dbf')

df_new = df[['CD_MUN', 'NM_MUN', 'SIGLA_UF', 'AREA_KM2', 'geometry']].copy()
#df_new = df[['CD_MUN', 'NM_MUN', 'SIGLA_UF', 'AREA_KM2']].copy()

#Filtra somente do estado da Paraíba
df_new = df_new[df_new['SIGLA_UF'] == 'PB']

df_new = df_new.sort_values(by='NM_MUN')
df_new = df_new.reset_index(drop=True)

df_new

# prompt: combinar df_new e eleitorado em um só dataframe

join_df = df_new.join(eleitorado)
join_df

from textwrap import fill
from re import L
m = folium.Map(location  = [-7.230933, -35.881844], zoom_start=8)

# Set the CRS to WGS84 (EPSG:4326)
join_df = join_df.set_crs(epsg=4326, allow_override=True)

# Inspect the structure of the join_df to understand how municipality names are stored
#print(join_df.head())

# Criando os limites personalizados (quantis)
bins = list(join_df['Total'].quantile([0, 0.2, 0.4, 0.6, 0.8, 1]))

folium.Choropleth(geo_data=join_df, name = 'Município', data = join_df, columns= ['Município', 'Total'],
                  key_on='feature.properties.Município', nan_fill_color='white', fill_color='plasma', threshold_scale=bins,
                  fill_opacity=0.7, line_opacity=0.2, legend_name='Total eleitores por município').add_to(m)

#Adiciona interatividade
folium.GeoJson(join_df, style_function=lambda feature: {'fillColor': '#ffffff00', 'color': 'black', 'weight' : 1, 'fillOpacity': 0},
               tooltip=folium.features.GeoJsonTooltip(fields=['Município','Total'], aliases=['Cidade:', 'Total:'], localize= True)).add_to(m)

m

m.save('eleitores_da_paraiba.html')

m

